import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Suspense } from "react";
import Loading from "./loading";
import { Toaster } from "react-hot-toast";
import { UserContextProvider } from "@/userContext/Usercontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserContextProvider>
          <Header />
          <div>
            <Suspense fallback={<Loading />}>
              {children}
              <Toaster />
            </Suspense>
          </div>
        </UserContextProvider>
      </body>
    </html>
  );
}
